// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsMR0i9_8EF1F-73u-8IKTopNGtvCx2Cw',
    appId: '1:129393086992:web:8f96104554070b1600f095',
    messagingSenderId: '129393086992',
    projectId: 'foodapp2025',
    authDomain: 'foodapp2025.firebaseapp.com',
    storageBucket: 'foodapp2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBicANOcYe2kr1_7-YsOAaSk1S9agDezBw',
    appId: '1:129393086992:android:c7bcd3fb9fa7913400f095',
    messagingSenderId: '129393086992',
    projectId: 'foodapp2025',
    storageBucket: 'foodapp2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE97jLb0a-ZoYCou_Z437gWLHSXi9OY-0',
    appId: '1:129393086992:ios:eb8fcbe3d29ad2dd00f095',
    messagingSenderId: '129393086992',
    projectId: 'foodapp2025',
    storageBucket: 'foodapp2025.firebasestorage.app',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE97jLb0a-ZoYCou_Z437gWLHSXi9OY-0',
    appId: '1:129393086992:ios:eb8fcbe3d29ad2dd00f095',
    messagingSenderId: '129393086992',
    projectId: 'foodapp2025',
    storageBucket: 'foodapp2025.firebasestorage.app',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsMR0i9_8EF1F-73u-8IKTopNGtvCx2Cw',
    appId: '1:129393086992:web:8f58b4c1d0e6d41200f095',
    messagingSenderId: '129393086992',
    projectId: 'foodapp2025',
    authDomain: 'foodapp2025.firebaseapp.com',
    storageBucket: 'foodapp2025.firebasestorage.app',
  );
}
